### ISSUE TITLE
Drop frame when I miss in taiko mode

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-performance#109]
When I miss in taiko mode,fps will reduce.Even arrived 10 fps.
It difficult to play.

**Comment by smoogipoo** [comment]
This is the wrong repository.

If the issue is related to osu!stable, make an issue in https://github.com/ppy/osu-stable-issues .
If the issue is related to osu!lazer, make an issue in https://github.com/ppy/osu .
