### ISSUE TITLE
Support unconditionally re-computing the pp across all rulesets

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-performance#113]
Currently, the `all` command only supports "one of 'osu', 'taiko', 'catch',  and 'mania'". It would be really helpful if this supported an "all" option.

**Comment by Tom94** [comment]
What's the problem with `osu-performance all osu && osu-performance all taiko && osu-performance all catch ...`?

**Comment by smoogipoo** [comment]
Ah yep, was a bit short-sighted. That'll do it :)
