### ISSUE TITLE
High AR HDFL aim pp 

### ISSUE THREAD

**Issue by shadowshadow725** [ppy/osu-performance#119]
Reason: Hidden does not make aiming high ar cross screen jumps any harder than just flashlight itself. 
Proposal: Scale hidden bonous aim pp down as ar increase.

**Comment by Magnus-Cosmos** [comment]
The hidden bonus already decreases as AR increases

**Comment by owbra** [comment]
I do think it's worth taking another look at how the FL bonus stacks with other reading bonuses in general. High AR and HD are pretty irrelevant as sources of difficulty if the map is being played by memory.

**Comment by shadowshadow725** [comment]
I'm only saying that hidden should not award as much HD bonus aim pp. I know that hidden bonus is already decreased for high ar. But I don't think if someone is going to DTFLHR a map, they should just slap HD on it just to get some bonus pp without much diffculty increase. I don't think any mod combinations should have a situation where "This doesn't make the map any harder, let's just slap it on for some more pp".

**Comment by shadowshadow725** [comment]
> I do think it's worth taking another look at how the FL bonus stacks with other reading bonuses in general. High AR and HD are pretty irrelevant as sources of difficulty if the map is being played by memory.

Therefore I think HD shouldn't award pp unless ar is very low (ar 8 and under)

> The hidden bonus for aim already decreases as AR increases

I know that hd aim bonus is already decreased for high ar plays. But I think hd still adds diffculty to ar 11 even if the diffculty is minimal.

Lets say for whitecat's top play Yubi Bouenkyou (TV Size) by fieryrage 98.62% HDDTHR 1182pp 
DTHR with the same acc would be 1133pp 

Now let's look at fgsky's top play JUSTadICE (TV Size) by Oomori Seiko Extreme 94.94% HDDTHRFL 1260pp
DTHRFL with the same acc and miss count would be 1211pp

both plays gets 49 bonus pp for having hidden, but hidden actually makes whitecat's play harder. For fgsky's play it doesn't make much of a difference. 
@owbra @Magnus-Cosmos

**Comment by Dawnsday** [comment]
OP, HD does make a major difference for FL plays. FL on it's own is much less "memory" than you seem to be /baselessly/ assuming. 

I reccomend looking at FL leaderboards then comparing them to the HDFL leaderboards, on less farmy maps (to be specific), I'd also reccomend you actually try to play the mod yourself, with and without hidden.

I'd argue FL is one of the few cirucmstances in the game where hidden is an objective difficulty increase, even on higher AR's (10.3+).

**Comment by shadowshadow725** [comment]
I agree that hdfl makes some high ar maps harder, but I think it only makes map where objects are mostly clustered together harder. (Think of stream maps with weird pattern) But these kind of map rely on flow aim which I have no intension to nerf. Also the point of this nerf is to stop "This doesn't make **the hard part of the map** any harder, let's just slap it on for some more pp"

Hidden makes plays like these a lot harder

Taiko no Tatsujin - Haya Saitama2000 97.97% FL  298pp by -GN
https://osu.ppy.sh/beatmapsets/9917#osu/39076
Aoki Chihiro - Kodou 99.05% HDHRFL 503pp  by -GN 
https://osu.ppy.sh/beatmapsets/687511#osu/1579923


But I don't think it makes these plays any harder to excecute 

Will Stetson - Harumachi Clover (Swing Arrangement) [Dictate Edit] 98.28% HDDTFL 720pp by fieryrage 
https://osu.ppy.sh/beatmapsets/842412#osu/1764213
JUSTadICE (TV Size) by Oomori Seiko Extreme 94.94% HDDTHRFL 1260pp by fgsky
https://osu.ppy.sh/beatmapsets/983942#osu/2058788

Since most of the diffculty of these maps that only comes from a small section of the map consisting of cross screen jumps and I don't think ar11/10.3 are reactable with FL. In my opinion these parts are being played purely with memory. 
@Dawnsday

**Comment by Dawnsday** [comment]
> Also the point of this nerf is to stop "This doesn't make **the hard part of the map** any harder, let's just slap it on for some more pp"

no one thinks that, HD is an objective difficulty increase with FL. You don't just "slap on" hidden to a flashlight play with one or two tries, it comes with a great deal more effort


> But I don't think it makes these plays any harder to excecute

"You don't think" and yet you have 0 experience with the mod? I'll tell you now, it does make those plays harder to execute. You are not able to properly gauge where you are aiming in relation to the notes, you have no approach circles to help you identify movement etc. What you "think" is contradictory to reality.

**Comment by MBmasher** [comment]
Instead of implementing bandage fixes like these, we should be working on creating a more complex system designed for FL (Most likely making a skill for FL and HDFL)

**Comment by shadowshadow725** [comment]
https://drive.google.com/file/d/1Fs0KYOQVQvfV2VRgHUFhYnh95Ync_ZnF/view?usp=sharing
This is a video of fgsky's replay without hd with frame counter. The video is recorded at 60 fps to match his refresh rate and slowed down to 10% speed. 

The object hit on frame 3244 has pretty much no indication of the location of the hit circle. HD or not it wouldn't make a difference. Considering this is the diffculty spike, this is the reason that I think HD doesn't affect the diffculty of the map too much. 

I do agree that the current pp system needs to be completely re done.
