### ISSUE TITLE
osu!mania NF multiplier in code doesn't match live

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-performance#121]
[Code here](https://github.com/ppy/osu-performance/blob/master/src/performance/mania/ManiaScore.cpp) shows that the NF multiplier is 0.9x, but looking at NF scores on any beatmap, it's all 0 pp

Example beatmap: https://osu.ppy.sh/beatmapsets/1071024#mania/2241878
![](https://i.imgur.com/Of1z0nw.png)

**Comment by cl8n** [comment]
i don't have a code reference but iirc all mania scores under 500k have 0pp. it was to prevent people mashing hard maps for rank

**Comment by cl8n** [comment]
nevermind here it is https://github.com/ppy/osu-performance/blob/master/src/performance/mania/ManiaScore.cpp#L86-L88

**Comment by abraker95** [comment]
Wow so NF multiplies PP by 0.9, but that doesn't matter because NF also halves score and that makes PP always 0.

**Comment by Zyfarok** [comment]
yep as @FullTablet said, it's re-scalled to remove the mod multiplier right here :
https://github.com/ppy/osu-performance/blob/master/src/performance/mania/ManiaScore.cpp#L78
So the error in calculation probably comes from somewhere else outside of ManiaScore.cpp.

I tried searching in the code at what other places the NF mod do have any impact but couldn't find anything yet. Running the pp calculation of a NF play in debug mode in some IDE and tracing back the source of the 0 in the step by step calculation is probably the easiest way to find it, but I've never used C# IDEs/tools.

**Comment by cl8n** [comment]
woops, sorry for the misleading comments then

**Comment by Zyfarok** [comment]
Ok nevermind I just found why :

1- The scoreMultiplier is recovered using `beatmap.DifficultyAttribute(_mods, Beatmap::ScoreMultiplier)` here :
https://github.com/ppy/osu-performance/blob/master/src/performance/mania/ManiaScore.cpp#L70

2- The DifficultyAttribute method is defined here and only considers a subselection of mods using MaskRelevantDifficultyMods
https://github.com/ppy/osu-performance/blob/master/src/performance/Beatmap.cpp#L22-L24

3- Of course MaskRelevantDifficultyMods ignores NF :
https://github.com/ppy/osu-performance/blob/92b3eaf832f79eb3e0731c4ce75a8944a2e7b48f/include/pp/Common.h#L98-L100
