### ISSUE TITLE
Requesting aim/speed/acc data for ranked maps

### ISSUE THREAD

**Issue by shavitush** [ppy/osu-performance#2]
https://www.reddit.com/r/osugame/comments/4fvtuf/pp_goes_opensource/d2cj2v4

> Make an issue asking for data on the pp repo and I'll get that done today or tomorrow.

**Comment by peppy** [comment]
Here's the attributes table for maps ranked in the last year:

https://puu.sh/orpn7/68a8157774/osu_beatmap_difficulty_attributes.7z

You may need to use the public API to get some other data (countNormal for instance) but this should suffice in reducing the effort required to dive in and help make possible improvements.

**Comment by peppy** [comment]
Here's the structure and lookup table that may also be helpful:
```
CREATE TABLE osu_beatmap_difficulty_attribs
(
    beatmap_id MEDIUMINT(11) UNSIGNED NOT NULL,
    mode TINYINT(3) UNSIGNED NOT NULL,
    mods INT(8) UNSIGNED NOT NULL,
    attrib_id TINYINT(11) UNSIGNED NOT NULL COMMENT 'see osu_difficulty_attribs table',
    value FLOAT,
    CONSTRAINT `PRIMARY` PRIMARY KEY (beatmap_id, mode, mods, attrib_id)
);

CREATE TABLE osu_difficulty_attribs
(
    attrib_id SMALLINT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) DEFAULT '' NOT NULL,
    visible TINYINT(1) DEFAULT '0' NOT NULL
);

INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Aim', 1);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Speed', 1);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('OD', 0);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('AR', 0);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Max combo', 0);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Strain', 1);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Hit window 300', 0);
INSERT INTO osu.osu_difficulty_attribs (name, visible) VALUES ('Score multiplier', 0);
```

**Comment by kimoi** [comment]
Is there any possibility to get a larger data set than just ranked maps in the last year?

**Comment by peppy** [comment]
Eventually, yes. For now, this should be enough to help out with the project. Let us know if you have a specific case where you require more data to help out.

**Comment by kimoi** [comment]
It's for a separate project I'm working on - it's a program to analyse common patterns/characteristics in maps. Having the difficulty attributes would be another useful metric I can throw at it.
