### ISSUE TITLE
HD: Fundamentally Flawed and Here Is Why

### ISSUE THREAD

**Issue by Xexxar** [ppy/osu-performance#31]
Before I start I want to make an explanation of who I am and why you should consider my point of view. I am a student who is graduating in less than two weeks with a major in mathematics and have been a member of the osu!community for 5 years. I have been a mapper for over 4 of those years and in my naive phases of mapping I intentionally tried to abuse the algorithm multiple times to make my maps more popular. I am aware of what the flaws of the system are and I fundamentally understand the roles of both speed, accuracy, and aim and how they are measured and calculated in the current system. 

With that out of the way, let's begin.

Under the current algorithm, the role of the hidden mod is to give an arbitrarily defined bonus of a approximately 1.18 multiplier to aim and a 1.02 multiplier to accuracy. Based on how aim is calculated, this implies that hidden gets more difficult as objects, in this case jumps, are spaced farther apart from each other. This is rather non-intuitive, as fundamentally HD does not get harder because an object is more spaced than another, it gets harder because of object density among other more complex factors. 

While I believe this to be self evident, I believe it's also important to consider the professional scene of players and how they utilize HD. In the top scene of players, we can see that almost all of them use HD for songs that do not have high speed difficulties. Even players that seem to always use HD for top scores will sometimes not use it for songs that are primarily stream heavy. For example, Vaxei (Donkey Kong) uses HD for all his top scores except for DragonForce - Seasons [Legend] +HR. We also see Mathi using HD for almost every aim map, but for his score on VINXIS - Sidetracked Day [Three Dimensions] +HR, he does not use it. 

In addition to this, top stream players such as Idke or lain almost exclusively avoid the mod on stream maps due to multiple reasons. One likely reason is the fact that there is little bonus to maps that are stream heavy with HD, but another reason that makes more sense is that it's not worth the bonus they get for the added difficulty. This should make it clear that something is not correct with how the algorithm awards bonus PP for the HD mod.

What can be done is very simple. Change the algorithm to give the bonus to speed instead of aim. This does not have to be an 100% transfer of the 1.18 multiplier, rather it could be a hybrid of both. For example.

Current Algorithm
`((aim*1.18)^(1.1)+(speed)^(1.1)+(acc*1.02)^1.1))^(1/1.1)*1.12`

Potential Algorithm
`((aim*1.05)^(1.1)+(speed*1.15)^(1.1)+(acc*1.02)^1.1))^(1/1.1)*1.12`

I am posting this in it's infancy to get your perspective on it and will gladly work to further develop documentation as well as collect data on how this will impact the top 1000 players through your databases provided through your website. Here is an example of what this algorithm would do to some map data I have created using Google Spreadsheets

http://puu.sh/Ae3zh/b0bc1de403.pdf

Bear in mind that the exact workings of the algorithm are subject to change. Personally, since speed values are typically lower than aim, I think a larger speed multiplier may be good thing, such as 1.2.

**Comment by Nodebuck** [comment]
Just a heads-up on your methodology. Cookiezi's Blue Zenith HDHR score would be buffed to 739.50pp and therefore replace his HR-only score. I didn't check whether there's further occurrences in the sample data though.

**Comment by Xinnoh** [comment]
hi reddit

**Comment by Tom94** [comment]
I welcome this change, especially since HD _can even make reading easier_ for very high AR maps. The one thing that definitely gets harder is following spaced streams, which currently is indeed reflected by the `Speed` component. Originally I had hoped to some day capture this in the `Aim` component instead, since, well, it has nothing to do with actual speed and everything with aiming correctly, but I don't see that happening in the near future.

Wanna implement your change and make a PR? This will also be a good opportunity to try out the latest version of osu!performance officially behind the scenes. :)

PS: Small fun-fact on the side. I know I am an outlier, but I play exclusively with HD and perform _worse_ without it.

**Comment by Xexxar** [comment]
I'll implement the change and make a PR after my final today. Glad you also agreed with my interpretation of this old oversight.

**Comment by Francesco149** [comment]
what do you think about the effect this will have on HDFL scores? I feel like on HFDL jumps are harder than streams, but I'm not a FL, HDFL player so I'm not sure

**Comment by Xexxar** [comment]
Under the current algorithm I believe the HD and FL multiplers are added in a multiplicative sense, so I am considering looking at how we can better balance this change as well. Either we can simply increase the multiplier for FL on `aim` or we can come up with a new weighting system for when both HD and FL are used. 

Personally I think increasing the multiplier on FL is fine for now. I'll need to look at the numbers and play around with it before submitting the PR.

**Comment by Francesco149** [comment]
I guess you could also not apply the rebalance on FL scores and that would be fine, I havent looked at the code tho so not 100% sure

**Comment by andremacareno** [comment]
Ange du Blanc Pur is mostly moderate BPM streamy map with a few spaced parts, right? As far as I remember, the PP system consider spaced streams as aim-heavy parts so how did you managed to increase the PP output with aim bonus reduction? I understand why it happens with Midnight Siege and Freedom Dive, but what will happen with maps containing both stream and jumps in almost equal numbers like PoNo’s Through the Fire and Flames and GoldenWolf’s Demetori maps?

**Comment by wxv** [comment]
[Xexxar's Best... Girl?!]

Slight boost for AR 8 and lower? Maybe optimistic but AR affects object density kinda

**Comment by EdrowsLuo** [comment]
EZHD = CRAZY

**Comment by Xexxar** [comment]
Well I guess I'll close this since it's been applied.
