### ISSUE TITLE
Rebalance pp awarded for flashlight plays

### ISSUE THREAD

**Issue by MBmasher** [ppy/osu-performance#44]
Right now, the way FL affects pp is that it gives a multiplier to aim pp 1.45 * length bonus, and also a 1.02 multiplier to acc pp. The problem here is that the FL multiplier uses the length bonus used for normal pp as its base. The length bonus is designed in a way that it doesn't benefit extremely long maps too much. This is done by giving less and less of a bonus the more objects, eventually ending in a logarithmic curve. This is the exact opposite of what we want in a FL system. The current system doesn't use any logarithmic curve, it just stays linear. This gives short maps significantly less of a bonus and long maps significantly more.

My proposed algorithm for a new FL aim multiplier is:

`under 500 objects: 1 + objects/900`

`above 500 objects: 1 + 500/900 + (objects-500)/600`

[Here is an image showing what this algorithm does to some FL plays, and a graph of a comparison between the old multiplier and the proposed multiplier.](https://i.imgur.com/JPInYaS.png)

The exact numbers may change, but the main points of this new algorithm is that:

1. The base multiplier at 0 objects starts at 1, as opposed to the old system which starts at 1.3775. This means that short maps will get a lower bonus.

2. The whole algorithm is linear. This means that long maps get more of a bonus. The old system had a logarithmic curve, which meant that the more objects, the lesser change in the multiplier.

There are still problems, of course. There is much more to a map's difficulty in terms of FL than just object count. But, this will hopefully fix the under/overweight problems of FL on the majority of maps. This is not perfect, but it seems like a good starting point.

**Comment by MBmasher** [comment]
After gaining some opinions from others, I've changed the algorithm to this:

`under 250 objects: 1 + objects/700
between 250-500 objects: 1 + 250/700 + (objects-250)/900
above 500 objects: 1 + 250/700 + 250/900 + (objects-500)/1200`

**Comment by smoogipoo** [comment]
Closing - implemented in the aforementioned 2 PRs.
