### ISSUE TITLE
HD Rebalance - A Deeper Look

### ISSUE THREAD

**Issue by NoMoreDiv** [ppy/osu-performance#45]
Firstly it’s great to see some changes finally being suggested, and being implemented towards the issue that is the Performance Points system, and more specifically towards the huge impact that the Hidden mod has in its current state.

However there are some major issues regarding the recently merged - and soon to be deployed - HD nerf proposed by Xexxar.

On the surface the change looks pretty good. We see an increase to PP for HD streams, and we see a decrease to PP for HD jumps, and when we check the scores from the top 15 players, we get a result that looks close to what we are aiming for. A nerf to HDDT farming, and a nice buff for underweighted stream maps. The only issue that stands out here, is the fact that the top 15 players are not an accurate representation of the entire osu! Community.

Before we compare some scores I’d like to make clear why HD is being targeted rather than DT directly. HD is considered by most, to not increase the difficulty of a map by much - especially at higher Approach Rates (as the time between the circle disappearing, and the moment you click it decreases) - and therefore is taken by many players when they play higher AR, because it is seen to be “free PP”. “HD can even make reading easier for very high AR maps” - Tom94

Now that we understand the context, let’s take a look at two types of scores; HD/HDHR plays, and HDDT plays, around the same pp value pre-nerf.

Below are some scores from each playstyle before and after the change. If all is going to plan with the re-balance then we should see a decrease in PP for HDDT and HD aim scores and an increase in PP for stream heavy maps.

[Comparison of HD, HDHR, and HDDT scores](https://puu.sh/AjgZj/c912ab449c.png)

Now although we do see a decrease to HD aim scores, we also see that HDDT actually gets hit less than HDHR and HD only aim scores. On top of this the increase in PP we should see to stream heavy maps is barely noticeable, with scores such as Dendei - gabe power +HD,HR gaining less than 0.5% PP. In fact compared to the change that aim receives, streams are barely changed at all without looking at extremely spaced streams, the likes of which we really only see from the top handful of players. This means that for the average 4-5 digit osu! player, HD streams are left basically untouched.

If we were to compare scores from slightly lower ranked players, we would see much the same thing, amplified due to how little lower spaced streams are buffed comparatively.

As far as fixing this flaw goes, I am suggesting that instead of hitting all scores containing HD with a flat nerf to the multiplier eg. 
`((aim*1.18)^(1.1)+(speed)^(1.1)+(acc*1.02)^1.1))^(1/1.1)*1.12 `
Being changed to 
`((aim*1.05)^(1.1)+(speed*1.15)^(1.1)+(acc*1.02)^1.1))^(1/1.1)*1.12 `
We can scale this aim multiplier with the AR of the map. The higher the AR on a map, the easier HD is to play on said map compared to no HD, and hence the less PP should be awarded for playing HD.

I am currently working with a group of people to come up with numbers for this change, however we fully believe that this is a better option than the current nerf.

In implementing this change we should see a similar situation with top players as with the current nerf, we will see a general nerf to HD aim, with the emphasis being on DT and high AR’s, but unlike the current nerf the trend should continue through all rank ranges. As for streams the buff from this will be greater in terms of percentage due to the aim nerf being more prominent in very high AR, while still being a nerf to HD aim overall, as well as lower AR streams being buffed even more.

**Comment by Xexxar** [comment]
I would argue we should keep the current bonuses but change the bonuses for AR lower than 9. Currently there is an if statement that gives bonuses for AR lower than 8, as seen here:

```
else if (approachRate < 8.0f)
	{
		// HD is worth more with lower ar!
		if ((_mods & EMods::Hidden) > 0)
			approachRateFactor += 0.02f * (8.0f - approachRate);
		else
			approachRateFactor += 0.01f * (8.0f - approachRate);
        }
```

Perhaps what could be done is raise it up to anything below AR9 and use MS of the AR rather than the value itself for scaling. This way EZHD would also get bonuses. We could increase the weighting as well. 

This nerf isn't really focused towards DT as you worded it, its focused towards nerfing aim. As explained before, HD does not get harder because a note is more spaced, so keeping a multiplier there doesn't really make sense. I'm more than willing to help buff lower AR HD plays, but plays that are HD only at 190 bpm with no streams and all jumps do not deserve alot of extra PP for HD. 

I would rather give a bonus to acc for HD than aim to be honest.

**Comment by NoMoreDiv** [comment]
Imo buffing very low AR's seems redundant, because maps with EZ will never give substantial PP anyway because of the acc values. My target range here is 9-11. 
But if starting from 11 and working down then I agree using the MS of the AR is exactly what I had in mind.
Also you note that higher spacing on the same jump does not make HD any harder to read. This is incorrect. When you aim any jump, HD or nomod, the time that you are moving your cursor between the notes, your brain is calculating trajectory and allowing you to make subtle changes to the way you are aiming. When extending the jump size with HD, your brain has LESS time to adjust trajectory than if the jump was the same pattern/object density, but smaller spacing, therefore causing your initial angle to need to be more precise. 
Maybe this means the bonus is better added onto speed - though I'm not entirely sure how this works.

**Comment by Xexxar** [comment]
Your point that the brain has less time to adjust trajectory is true for both HD and nomod. The process of identifying the distance and the amount you have to move is universal, regardless of whether or not you're using HD. You see the note, calculate where your hand needs to move, and you move to that spot. That is true for either HD or nomod, so why should HD get a bonus for it?

This is not a nerf to HD or HDHR players. It is a nerf to players who only play jump maps with HD. If those players branch out into streams with their hidden skills they will raise substantially through the ranks. HD on just jump maps deserves a nerf, regardless of the mod. As Tom94 said, there are many players who find HD easier on aim maps. Hidden will always be hard to balance because the map is fundamentally the same when you apply the mod, which is why this rebalance just tries to address what skills regarding HD are actually underrepresented: Streams.

**Comment by NoMoreDiv** [comment]
What I have said is not true for nomod, identifying the distance and amount you have to move is one thing, but not exactly what I'm talking about. I'm referring to the actual subtle changes you make **while in motion**. With nomod the note never leaves the screen. You can keep doing these path alterations right until the moment you click the note. You cannot do this with HD as the note leaves the screen entirely. Any path alteration after this is purely memory of where the note was. 
The aim difficulty this brings becomes less the higher the AR, as the note is off the screen for less time.
That's why HD should get a bonus for it.

> As Tom94 said, there are many players who find HD easier on aim maps.

This is a misquote, Tom specifically mentions higher AR's as a I refer to in my post.

I don't disagree that HD aim is over-weighted, that was never in question. The issue here is that you're not looking at the thing that makes it so.

The things that give HD it's difficulty (other than what I just talked about with spacing) are note density, and AR - or the time the note is actually disappeared from the screen. By buffing the speed multiplier we are tackling of the issues presented by note density, however AR is still relevant for the same reason I address above.

I am still all for nerfing HD jumps, and buffing HD streams. 
If we agree that AR is relevant to HD aim then the severity of the nerf on the mod combinations should be as follows.
HDDT > HDHR/AR10 > HD
Where HDDT refers to maps played with AR>10; HDHR/AR10 refers to maps played with AR=10, which includes HD only AR10; and HD refers to maps AR<10.

**Comment by Xexxar** [comment]
As a player, I have never adjusted my aim mid snap because I move my pen to snap to where the note is. How can you adjust your aim during a cross screen jump? It's purely a snapping motion and HD and nomod will struggle the same way. 

I would be willing to build a AR sensitive scaling bonus to aim with HD, since I do agree that there is an issue, but you realize this is just going to buff AR 8 DT and nerf HDHR? I don't really think this is the right approach, because its not the heart of the problem. If anything, buff HD for aim on smaller circles, since it is reasonably more difficult to hit notes on HD that are small than large ones, but AR does not necessarily guarantee a harder map on HD. I personally find HD easier on nomod than HR for example.

**Comment by Soukyuen** [comment]
I literally do not know anybody that thinks HD makes jumps any harder. In fact they all think it allows for less distraction on the screen, since like xexxar pointed out, any jumps for maps above 5 stars would barely leave any time to allow you to adjust mid snap. I am also in agreement that the 'advantage gained from the note staying on the screen' would only apply to maps that are much slower.

**Comment by Sakisan** [comment]
Here are [the scores from the opening post](https://puu.sh/AjgZj/c912ab449c.png) again with the formula from the PR `_aimValue *= (1.02f+(11.0f - approachRate)/50.0f);`

(scroll to the right to see the values or [see it on hastebin](https://hastebin.com/uditosetop))
```
ClariS - Hitorigoto -TV MIX- (Doormat) [Xxdeathx's Insane].osu                                                              [Hidden,DoubleTime]     420.94  406.40  -3.46%
ArsMagna - Himitsu o Choudai (Kyubey) [Insane].osu                                                                          [Hidden,DoubleTime]     404.61  396.57  -1.99%
ClariS - Hitorigoto -TV MIX- (Doormat) [Kencho's Insane].osu                                                                [Hidden,DoubleTime]     390.70  382.50  -2.10%
Elmo and Cookie Monster - Cookie-Butter-Choco-Cookie (Monstrata) [Cookie-Triangle-Spicy-Cookie].osu                         [Hidden,DoubleTime]     389.08  372.80  -4.19%
Ito Kanako - Skyclad no Kansokusha (N a s y a) [Guy's Insane].osu                                                           [Hidden,DoubleTime]     380.40  378.12  -0.60%
supercell - Kimi no Shiranai Monogatari -TV Edit- (walaowey) [Insane].osu                                                   [Hidden,DoubleTime]     379.68  373.70  -1.57%
sana - Kotoba no Iranai Yakusoku (TV size) (monstrata) [Six Paths].osu                                                      [Hidden,DoubleTime]     374.53  372.27  -0.61%
Petit Rabbit's - Takarabako no Jet Coaster (Taeyang) [Jet Coaster].osu                                                      [Hidden,DoubleTime]     373.27  364.30  -2.40%
SawanoHiroyuki[nZk]mizuki - &Z (TV size) (Umi) [xChippy's Insane].osu                                                       [Hidden,DoubleTime]     371.66  361.44  -2.75%
Fujijo Seitokai Shikkou-bu - Best FriendS -TV Size- (Flask) [Fycho's Insane].osu                                            [Hidden,DoubleTime]     370.37  358.82  -3.12%
Wada Kouji - Butter-Fly~tri.Version~ (Kencho) [Butter-Fly].osu                                                              [Hidden,DoubleTime]     369.54  367.67  -0.51%
Tristam - Once Again (grumd) [Insane].osu                                                                                   [Hidden,DoubleTime]     360.60  355.27  -1.48%
Katarzyna Laska - No Ordinary Girl (Tidek) [Insane].osu                                                                     [Hidden,DoubleTime]     360.05  353.14  -1.92%
Syaro(CV.Uchida Maaya) - Caffeine Fighter (Doormat) [Kilimanjaro].osu                                                       [Hidden,DoubleTime]     353.74  345.75  -2.26%
ARCIEN - Future Son (Mishima Yurara) [N A S Y A'S OK DAD].osu                                                               [Hidden,DoubleTime]     352.82  338.97  -3.93%
Ayase Rie - Yuima-ruWorld TVver. (Fycho) [Extra].osu                                                                        [Hidden,DoubleTime]     352.42  337.00  -4.37%
supercell - Kimi no Shiranai Monogatari (SoGa) [Moecho's Monogatari].osu                                                    [Hidden,DoubleTime]     347.05  341.59  -1.57%
mimimemeMIMI - Harebare Fanfare (Luna-) [Bright & Cheerful].osu                                                             [Hidden,DoubleTime]     344.90  332.07  -3.72%
ClariS - Hitorigoto -TV MIX- (Doormat) [Soliloquy].osu                                                                      [Hidden,DoubleTime]     340.07  327.77  -3.62%

petit milady - Hakone Hakoiri Musume (Rizia) [Simple].osu                                                                   [Hidden]                402.19  389.28  -3.21%
petit milady - Hakone Hakoiri Musume (Lami) [Hakone].osu                                                                    [Hidden]                400.50  387.94  -3.14%
fourfolium - Now Loading!!!! (Doormat) [Press SELECT].osu                                                                   [Hidden]                396.21  381.07  -3.82%
Dendei - gabe power (HighTec) [Brain Dog].osu                                                                               [Hidden,HardRock]       394.02  397.36  0.85%
Noboru feat.Mitani Nana - Shiroi Yuki no Princess wa (Natsu) [Snow White].osu                                               [Hidden]                387.17  390.41  0.84%
nao - Toaru Shoukoku no Ohimesama ga... (Lami) [Princess].osu                                                               [Hidden]                385.33  376.05  -2.41%
Ayaponzu - Streaming Heart (Lasse) [Ambiguity].osu                                                                          [Hidden]                385.02  376.06  -2.33%
MY FIRST STORY - Smash Out!! (FCL) [Extreme].osu                                                                            [Hidden]                370.81  363.72  -1.91%
petit milady - Hakone Hakoiri Musume (Rizia) [lit120's Extra].osu                                                           [Hidden]                362.32  355.93  -1.77%
Suara - Amakakeru Hoshi TV ver. (Taeyang) [Masquerade].osu                                                                  [Hidden]                360.04  343.41  -4.62%
nano - Bull's eye (Chloe) [Skystar's Extra].osu                                                                             [Hidden,HardRock]       357.68  342.06  -4.37%
nano - Bull's Eye (Asphyxia) [Last Trigger].osu                                                                             [Hidden]                356.75  357.80  0.30%
Yuaru - Asu no Yozora Shoukaihan (Akitoshi) [Sky Arrow].osu                                                                 [Hidden]                347.24  347.88  0.18%
Reol - No title (VINXIS) [jieusieu's Lemur].osu                                                                             [Hidden]                347.11  330.18  -4.88%
Manami Numakura - Sakebe (Meg) [Shout!].osu                                                                                 [Hidden]                347.05  335.88  -3.22%
Izumi Akazawa (CV. Madoka Yonezawa) - Responsibility Response (Shmiklak) [Slayed's Answer].osu                              [Hidden,HardRock]       344.40  324.72  -5.71%
TheLaxOne - Skrillex Circulation (grumd) [Rekt!].osu                                                                        [Hidden,HardRock]       343.74  332.90  -3.15%
ClariS - Hitorigoto -TV MIX- (Doormat) [Soliloquy].osu                                                                      [Hidden,DoubleTime]     343.66  330.15  -3.93%
Primary - Inai Sekai (Shad0w1and) [Kimi ni Todoku Ka Na].osu                                                                [Hidden]                342.17  330.12  -3.52%
Nekomata Master - Avalon no Oka (moph) [Special].osu                                                                        [Hidden]                340.31  333.93  -1.88%
```
