### ISSUE TITLE
[osu!std] Some old maps award 0 acc pp because of 0 hit objects

### ISSUE THREAD

**Issue by LazyLea** [ppy/osu-performance#53]
List of affected maps:
https://osu.ppy.sh/b/97
https://osu.ppy.sh/b/107
https://osu.ppy.sh/b/159
https://osu.ppy.sh/b/161
https://osu.ppy.sh/b/183
https://osu.ppy.sh/b/207
https://osu.ppy.sh/b/238
https://osu.ppy.sh/b/250
https://osu.ppy.sh/b/305
https://osu.ppy.sh/b/369

According to the sql data dump "2018_05_17_performance_osu_top.tar.bz2" the respective `countTotal`, `countNormal`, `countSlider` and `countSpinner` fields of these maps all equal `0`.

I'm not sure whether this is intended behavior or a bug that's either been overlooked or disregarded, so I wanted to report it somewhere.

**Comment by peppy** [comment]
Well spotted! Will look into a fix for this at a database level.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment]
All of these have now been fixed. PP should be awarded next full reprocess (we will be doing one soon due to pp changes).
