### ISSUE TITLE
Does not compile on OS X

### ISSUE THREAD

**Issue by numbermaniac** [ppy/osu-performance#6]
`cmake` works successfully, but `make` does not.

```
[  4%] Generating PrecompiledHeader.h.gch
/bin/sh: clang++-3.5: command not found
make[2]: *** [Src/Processor/PrecompiledHeader.h.gch] Error 127
make[1]: *** [Src/Processor/CMakeFiles/Client_PrecompiledHeaderDependency.dir/all] Error 2
make: *** [all] Error 2
```

OS X has clang and clang++ when you install Xcode, but clang++-3.5... well, bash says not found.

```
$ clang++ --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I couldn't find the word "clang" in any of the Makefiles, so I don't know how to fix it.

**Comment by Numbermaniac** [comment]
Ok, well I did find it in CMakeLists.txt so I changed the compilers to clang clang++. Now that's working, but I'm getting different errors about the code itself:

```
[  4%] Built target Client_PrecompiledHeaderDependency
[  8%] Building CXX object Src/Processor/CMakeFiles/Client_mac.dir/DDog.cpp.o
/Users/lleyton/Documents/osu/osu-performance/Src/Processor/DDog.cpp:91:9: error: thread-local storage is not supported for the current target
        static thread_local std::default_random_engine generator{
               ^
/Users/lleyton/Documents/osu/osu-performance/Src/Processor/DDog.cpp:92:3: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to
      'result_type' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
                std::hash<std::thread::id>()(std::this_thread::get_id())};
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/lleyton/Documents/osu/osu-performance/Src/Processor/DDog.cpp:92:3: note: insert an explicit cast to silence this issue
                std::hash<std::thread::id>()(std::this_thread::get_id())};
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                static_cast<result_type>(                               )
/Users/lleyton/Documents/osu/osu-performance/Src/Processor/DDog.cpp:93:9: error: thread-local storage is not supported for the current target
        static thread_local std::uniform_real_distribution<f32> distribution{0.0f, 1.0f};
               ^
3 errors generated.
make[2]: *** [Src/Processor/CMakeFiles/Client_mac.dir/DDog.cpp.o] Error 1
make[1]: *** [Src/Processor/CMakeFiles/Client_mac.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by Tom94** [comment]
Hi there, we do not officially support compiling on OS X and / or with clang. If you do not know how to resolve the compilation errors you could try installing a somewhat recent version of gcc and compiling with that instead of clang.

**Comment by Numbermaniac** [comment]
Alright. Small question though: It can't find libmysqlclient.so; assuming this comes with the MariaDB connector download (from the Linux instructions), where does it look for this file? Thanks @Tom94 .

**Comment by Tom94** [comment]
In your standard library paths (e.g. /usr/lib). All compilers support passing additional folders to look in via the command line. gcc does it with ne -L option.

**Comment by vendethiel** [comment]
btw, on os x, you'll need to `brew install llvm --with-clang`, because apple's clang disables `thread_local`.

**Comment by vendethiel** [comment]
open src/Processor/CMakeLists.txt, and change

```
libmysqlclient.so
libcurl.so
```

to

```
mysqlclient
curl
```

(`-l` will use dylib/so or whatever it needs, and it adds the `lib` prefix itself)

**Comment by Numbermaniac** [comment]
I already installed clang from the website because of that Apple restriction, but I didn't realise it goes as `llvm` within brew; no wonder I couldn't find it. Thanks!

Also, I did eventually figure out you have to change the names, but it now gets to 100% and complains about missing symbols for x86_64 architecture or something. Thanks though :)

**Comment by vendethiel** [comment]
Can you please post the error messages? I have it compilig and running on OS X.

**Comment by Numbermaniac** [comment]
@vendethiel It says "Undefined symbols for architecture x86_64:" followed by a bunch of code several times the height of my screen. I can put it in a text file if you want.

**Comment by vendethiel** [comment]
IIRC I just used brew

**Comment by Numbermaniac** [comment]
@vendethiel Would you happen to know which mysql library you installed from brew? I've used brew but it still gives me "Undefined symbols for architecture x86_64". Which one did you install? There seems to be quite a few of them with similar names.

**Comment by Lubb69** [comment]
Can someone do this for me, I have no idea how to do this. or can you just send in a file? or maybe make a video of you doing this so I can copy it? idk

**Comment by Tom94** [comment]
Works perfectly fine on macOS now.
