### ISSUE TITLE
Osu!Catch

### ISSUE THREAD

**Issue by O-X-E-Y** [ppy/osu-performance#67]
Could something like this be implemented in Catch too? This may partially fix broken maps like Image Material

Edit: I meant to comment on Xexxar's post, how do I delete this? ;-;

EDIT 2: After a quick google search I noticed it's impossible to delete this myself. I feel embarrassed, could a mod please delete this?

**Comment by Magnus-Cosmos** [comment]
You can close issue, don't think it's possible to delete.
