### ISSUE TITLE
Is the Strain calculation for Taiko also hidden like the aim/speed for Standard?

### ISSUE THREAD

**Issue by Numbermaniac** [ppy/osu-performance#7]
I've been looking at the code for Taiko and I can't find where the Strain value is calculated. Is it just not there or is it in a file I haven't looked at? Thanks :)

**Comment by Tom94** [comment]
It's in the osu! client's source code, just like the other game modes. Not intentionally hidden - just not duplicated across multiple projects. We use a headless (no graphical interface) version of the client to populate the values in our database. Once the osu! client goes open source you'll be able to see the calculation.
