### ISSUE TITLE
Accuracy formula change proposal

### ISSUE THREAD

**Issue by diamondburned** [ppy/osu-performance#75]
# Introduction

Recently, MBmasher has released a proposal asking for an accuracy change. While addressing some issues, I personally think the change was too harsh.

The proposal, in short, basically renders plays that have an accuracy lower than 85% trash (especially when it goes under 65%) due to how the algorithm is made. ~~The algorithm does reward a small amount of bonus when the accuracy goes over 95%, anything under 90% is quite noticeable nerfed.~~

An update has been made, and the formula now rewards a bit more for SS scores. The nerfing ceiling is now ~~95% like MBmasher's~~ 96.15%, though overall nerf is not as steep. Comparing to the old formula, it still gets more rewarding after 99.19%.

While this sounds reasonable when addressing proposed issues, I think it penalizes a lot of new players who want to try harder difficulties for themselves, or those stuck with a play style (eg mouse-only). Since these changes don't award them much, they won't try harder difficulties anymore, making the game not fun :( (though after a few changes, it just makes the curve more fair)

With that said, I have decided to make my own algorithm.

# The differences

- Line is no longer as steep
-  On the high accuracy range (~95% to 100%), there's still a nerf until 96.15% at OD11 (for reference, MBmasher's is 93.69%)
- Some constants from MBmasher's were used on mine
- MBmasher's peak bonus is 1.029, while mine is 1.0305 (for reference, originally it is 1.0284) (OD11)

# The Maths

## Pretty

![](https://ptpb.pw/ACpZ.png)

## [Graph](https://www.desmos.com/calculator/ll7pnlh1ie)

> Black: mine
> Pink: MBmasher's
> Green: Original

> X-axis: Accuracy
> Y-axis: Bonus

![](https://ptpb.pw/HjI9.png)

### LaTeX

```tex
\left(\frac{\left(\sin\left(\left(x^1+\frac{o_d^{\frac{1}{2}}}{k}\right)x^2\right)\right)}{\frac{o_s}{f}+0.35}\right)+a\left\{x\le1\right\}\left\{x>0\right\}
```

**Comment by VINXIS** [comment]
Added a new page to show pp changes of the same scores with this version: https://docs.google.com/spreadsheets/d/1SqR1KODW39M1tVmGYS16JismDoc1M2jmNAwWfjgmh_w/edit#gid=1323989680

**Comment by Iryya** [comment]
> I think it penalizes a lot of new players who want to try harder difficulties for themselves, or those stuck with a play style (eg mouse-only). Since these changes don't award them much, they won't try harder difficulties anymore, making the game not fun :(

Nothing is stopping new players to gradually learn the game, instead of skipping directly to high difficulties. Also, assuming that someone is going to quit just at the very start because they don't win enough pp is big statement. Not everyone plays for pp, and if someone does, is universally known that getting higher accuracy significantly gives more pp than FCing something difficult with bad accuracy. 

If anything, I personally think that having a low acc nerf is something really good for new players, as they are encouraged to learn how to properly read rhythm rather than picking your favorite aim map and mash your keyboard hoping for a FC.

**Comment by diamondburned** [comment]
I've made an update to the main post.

**Comment by diamondburned** [comment]
Updated again to address some of the issues VINXIS spotted out

**Comment by girantinas** [comment]
Looking at VINXIS' data, I don't think that people want 75% FCs near their top plays. I think the reasoning that suggesting that people will not push to the limits if the pp they get back is less. In truth, no experienced player sets low accuracy plays in hopes of gaining pp. Instead, the only ones who will suffer will be the newer players, who think setting low accuracy plays is acceptable in getting pp and the game rewards them for it. Plus it will stop all those people from having a C on Harumachi Clover or CBCC in their top plays (myself included).
