### ISSUE TITLE
The high AR Bonus is faulty (With possible solutions)

### ISSUE THREAD

**Issue by Spooneliate** [ppy/osu-performance#96]
**Problem**

Currently, scores done on high AR (10.33 to 11, only achievable by adding DT mod to an AR9+ map)  receive a bonus multiplier to their aimvalue and speedvalue for being able to read/react to it. This multiplier starts at 1.0x for AR10.33 and increases linearly up to 1.2x at AR11. 

The reasoning for this reward is not quite clear, due to there being multiple ways to tackle high AR maps which vary in difficulty depending on the map. 

One way a player can tackle a high AR map is by just being able to read/react to it using their raw reaction time. For these kinds of players, the reward makes (some) sense. However, there is another way players can tackle high AR maps, and that is by memorisation. For these players, memorising a 1000 object map on AR11 for a 1.2x bonus multiplier may not be worth it, which is understandable. However, the bonus does not change depending on length; Players who memorise high AR maps get an equal reward for memorising a 100 object map as a 1000 object map. Thus, there is no reason for players who can’t read high AR to play anything other than the shortest of maps. In fact, these players are being vastly over rewarded for memorising or partially memorising short maps with high AR.

Think about all the recent high pp scores that were AR11 or close. They are all almost exclusively short maps (I haven’t had a thorough check but I’d be willing to bet that all are under 500 objects). Think about all those high pp scores on very short maps. The vast majority have at least DT,HR plus other mods. A good example of a recent offender is: https://osu.ppy.sh/b/1893461?m=0
many players have made their top play or a top 5 play on this sort of map.

Chart of Maps with AR11 scores over 600pp (Slightly Old): https://i.imgur.com/j7EMetT.png

The issue gets even more complicated when you consider the fact that many times players are using a combination of both methods – their reaction time AND some loose memorisation – in order to get the high AR bonus.

**The solution(s)**

I’m partially of a mind to scrap the AR bonus completely, mainly due to the fact that it’s too simplistic of a fix for a complex subject. There may even be more factors affecting difficulty of high AR that haven’t been considered. However, after running the numbers, this is far too harsh and completely ruins all incentive to play high AR(for now).

A more compromising solution would be to assume the player is memorising shorter maps. With memorisation, the difficulty is negligible at 1 object, and linearly increases as the amount of objects in the map increases. For longer maps the player will be assumed to be reading/reacting the map, and so the multiplier will stop scaling based on number of objects and remain constant, as we don’t want to over reward players who are not doing any memorisation and instead just reading. The point where short map becomes long map is unclear though. I’ve decided to place it at 500 objects.

This makes:

```
	if (approachRate > 10.33f)
		approachRateFactor += 0.3f * (approachRate – 10.33f);
```

Become:

```
	if (approachRate > 10.33f)
		approachRateFactor += 0.3f * (approachRate - 10.33f) 
		* std::min(1.0f, static_cast<f32>(numTotalHits) / 500.0f);
```
Top 10 Scores before and after: https://i.imgur.com/nKc4EjB.png

Longer maps such as Best Friends and caffeine fighter remain unaffected by this change.

This is from an old database dump, so I’ll need an up to date database dump in order to properly test things.

**Conclusion**

The problem I am quite sure about. The solution I am still unsure of, but would like to continue exploring possibilities.

**Comment by Magnus-Cosmos** [comment]
I feel like this would erase the already little incentive for lower rank players to play AR11, I don't if that's considered a good or bad thing, but this change will nerf most low star rating AR11 plays. Though I guess you can argue that these plays have less significance than high pp plays.

**Comment by Spooneliate** [comment]
Interesting. I can't think of many examples of low star rating maps that are also AR11 AND are short. Do you have any particular in mind?

To me this is an equal nerf to every star rating, high or low. In fact, you could argue that it hits more difficult maps even harder than easier maps, given that the bonus is in the form of a multiplier, and so harder maps with a higher speed/aimvalue will lose more total pp.

**Comment by abraker95** [comment]
> Interesting. I can't think of many examples of low star rating maps that are also AR11 AND are short. Do you have any particular in mind?

Easiest one I know of is this https://osu.ppy.sh/beatmapsets/1137#osu/8734

**Comment by O-X-E-Y** [comment]
Besides the fact that a lot of new players have trouble playing even AR 10 let alone AR11, if I'm entirely honest I don't think there even _should_ be incentive for newer players to play high AR. Regardless of it potentially being a seperate skill or not, solely playing high AR from early on damages one's reading permanently and makes improving on anything other than doubletime really difficult. I suggest therefore that unless results really screw over low SR leaderboards, the focus should be put on higher level play, at least for now.

**Comment by matrix1337** [comment]
> Besides the fact that a lot of new players have trouble playing even AR 10 let alone AR11, if I'm entirely honest I don't think there even _should_ be incentive for newer players to play high AR. Regardless of it potentially being a seperate skill or not, solely playing high AR from early on damages one's reading permanently and makes improving on anything other than doubletime really difficult. I suggest therefore that unless results really screw over low SR leaderboards, the focus should be put on higher level play, at least for now.

Who in their right mind would say that we shouldn't give an incentive for newer players to play hard things because it'll apparently make them worse? I don't know what makes you assume playing high AR early on "permanently" damages your reading, it would only end up being bad because you never trained it in the first place and can still be trained normally.

**Comment by O-X-E-Y** [comment]
Never mind my half-asleep 5 digit opinion. I should probably keep my mouth shut on here, you guys know much better than I what you're doing
